-- require("nvim-treesitter.configs").setup({
--   ensure_installed = {
--     "go",
--     "lua",
--     "python",
--     "javascript",
--     "typescript",
--     "json",
--     "yaml",
--     "bash",
--     "css",
--     "graphql",
--   },
-- 
--   highlight = {
--     enable = true,
--   },
-- 
--   indent = {
--     enable = true,
--   },
-- })
